### ISSUE TITLE
Should extension methods have prefix, like ezs_?

### ISSUE THREAD

**Issue by paulz** [goktugyil/EZSwiftExtensions#109]
Thank you for the useful extensions!

We recently integrated EZSwiftExtensions into our production project and noticed some surprising breakages happening.

Removing EZSwiftExtensions fixed the issues.

We wonder if there is a subtle name clash going on with Apple internal method names since compiler did not give us any warning about conflicts.

When we ask Apple for support Apple Engineers recommended using a name prefix for extension names  to their classes to avoid potential conflict.

Is there any other way to avoid name clash?

**Comment by goktugyil** [comment]
Hello, I am also using this repo in several of my apps in production using Swifts latest version, there were no clashes?

Apple added some of the methods included here over the time, but we removed them. Which version of Swift and EZSwiftExtensions are you using? Which Apple or other peoples frameworks are you using? Did you install manually or as a framework from cocoapods?

Name prefixes sounds like a good idea to fix this problem, but I've never heard anyone experience this the problem is more likely to be extensions in this repo clashing with extensions in another open source repo

**Comment by inket** [comment]
Relevant: https://pspdfkit.com/blog/2016/surprises-with-swift-extensions/

Are you using Objective-C ?

I think it would be better to include a prefix for Objective-C like `@objc(ezs_)`

**Comment by paulz** [comment]
@goktugyil we use Swift 2 on ObjC+Swift project with many cocoapods. Latest release of cocoapods '0.39'. All targets `use_frameworks!`
We installed EZSwiftExtensions as a cocoapod.  
Here is our list of Apple frameworks:
```
MobileCoreServices.framework
Foundation.framework
UIKit.framework
CoreGraphics.framework
SystemConfiguration.framework
```

Unfortunately we did not had time to debug the problem and had to remove EZSwiftExtensions since we just started using it. Our application lost some colors when we had EZSwiftExtensions and we do use UIAppearance, if that matters.

Thank you again for very useful cocoapod!

**Comment by goktugyil** [comment]
I tried adding those frameworks, tried using objective-c. Still couldn't find a problem, can you give me the list in your podfile? Maybe something there is clashing

**Comment by paulz** [comment]
Here is the list of pods we use, all installed with `use_frameworks!` 
```
- ASRestKit (0.9.1) [Apache License, Version 2.0]
  ASRestKit is a collection of codes can be used as base of ios project using RestKit

- AFNetworking (3.1.0) [MIT]
  A delightful iOS and OS X networking framework.

- GRK-Mixpanel-OSX (2.8.1) [Apache License]
  OS X tracking library for Mixpanel Analytics.

- ComponentKit+SDWebImage (0.0.2) [MIT]
  CKNetworkImageDownloading implementation for SDWebImage.

- FBSDKLoginKit (4.11.0) [Facebook Platform License]
  Official Facebook SDK for iOS to access Facebook Platform with features like Login, Share and Message Dialog, App Links, and Graph API

- FBSDKShareKit (4.11.1-beta1) [Facebook Platform License]
  Official Facebook SDK for iOS to access Facebook Platform's Sharing Features

- MBProgressHUD (0.9.2) [MIT]
  An iOS activity indicator view.

- ZeroPush (2.1.2) [MIT]
  ZeroPush is a lightweight wrapper for the ZeroPush API.

- BMYCircularProgressPullToRefresh (1.1.1) [New BSD License]
  Pull to fresh with circular progress view as used in the Beamly iOS app.

- Objection (1.6.1) [https://github.com/atomicobject/objection/blob/master/LICENSE]
  A lightweight dependency injection framework for Objective-C.

- AVReachability (0.1.1) [MIT]
  Check network connectivity in iOS 9

- IQKeyboardManagerSwift (4.0.2) [MIT]
  Codeless drop-in universal library allows to prevent issues of keyboard sliding up and cover UITextField/UITextView.

- YourStatusBar (1.0.1) [MIT]
  Customize the iOS statusBar with your text or UIView

- Swinject (1.1.1) [MIT]
  Dependency injection framework for Swift

- ImageCoordinateSpace (0.3.1) [MIT]
  Convert image coordinates to image view depending on content mode

- KMPlaceholderTextView (1.2.0) [MIT]
  A UITextView subclass that adds support for multiline placeholder written in Swift.

- SwiftHEXColors (1.0.4) [MIT]
  HEX color handling as an extension for UIColor. Written in Swift.

- LTSwiftDate (0.1.0) [MIT]
  Easy-to-use NSDate operation

- PhoneNumberKit (0.7) [MIT]
  Swift framework for working with phone numbers

- TIPBadgeManager (0.3.0) [MIT]
  A simple module to create and manage multiple badges for iOS 8

- JSQNotificationObserverKit (5.0.0) [MIT]
  Generic notifications and observers for Cocoa and CocoaTouch

- Alamofire (3.3.1) [MIT]
  Elegant HTTP Networking in Swift

- AlamofireSwiftyJSON (0.1.0) [MIT]
  Alamofire extension for serialize NSData to SwiftyJSON

- Moya (6.4.0) [MIT]
  Network abstraction layer written in Swift

- Moya-SwiftyJSONMapper (1.0.3) [MIT]
  Map objects through SwiftyJSON in combination with Moya

- BFGCallbackRouter (1.0.1) [MIT]
  Simple URL router supporting the x-callback-url 1.0 DRAFT spec.

- SAConfettiView (0.1.8) [MIT]
  Confetti! Who doesn't like confetti?'

```

**Comment by goktugyil** [comment]
I couldn't get these to compile, which may be a lot of reasons like target version, objc stuff, or this repo. #pod 'ASRestKit'
#pod 'BFGCallbackRouter'
#pod 'GRK-Mixpanel-OSX'
#pod 'ComponentKit+SDWebImage'
#pod 'AVReachability'

The rest works fine

**Comment by lfarah** [comment]
Hey @paulz, do you still have problems with this?
I'll reopen the issue if you still need help
