### ISSUE TITLE
carthage update problem

### ISSUE THREAD

**Issue by phpmaple** [goktugyil/EZSwiftExtensions#115]
When I use carthage update failure and show many warning and error below info

```
*** Building scheme "EZSwiftExtensions-iOS" in EZSwiftExtensions.xcworkspace
config error: 'variable_name_min_length' is not a valid rule identifier
config error: 'valid_docs' is not a valid rule identifier
```

```
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/xxx/Library/Developer/Xcode/DerivedData/EZSwiftExtensions-hdalhogyszjhlnaluqlsmltwrjbs/Build/Intermediates/EZSwiftExtensions.build/Release-iphoneos/EZSwiftExtensions-iOS.build/Script-B27008081CAA12D5002177ED.sh
(1 failure)
```

**Comment by goktugyil** [comment]
@bcylin Can you check out this problem?

**Comment by bcylin** [comment]
I think it has something to do with SwiftLint in the build config. @phpmaple could you please provide the following info? Thank you.

* `xcodebuild -version`
* `carthage version`
* The `Cartfile.resolved`, or the version of EZSwiftExtensions that you are installing

**Comment by phpmaple** [comment]
- Xcode 7.3
Build version 7D175

- 0.11.0

- github "goktugyil/EZSwiftExtensions" "1.3"

**Comment by inket** [comment]
Your SwiftLint version might be outdated?

Try running `brew upgrade swiftlint`

**Comment by phpmaple** [comment]
@inket Thanks, it solved, I closed problem
