### ISSUE TITLE
Carthage support iOS SDK

### ISSUE THREAD

**Issue by JanusHuang** [goktugyil/EZSwiftExtensions#119]
Hi, when I use carthage to import the EZSwiftExtensions, I got the the error since the project base sdk is iOS 9.0 while mine is iOS 8.0, thus I have to modify the configuration manually and rebuild, can the author modify the project sdk to 8.0 thus we can keep our framework updated. No everyone's project use minimal sdk 9.0 right?

**Comment by goktugyil** [comment]
https://github.com/goktugyil/EZSwiftExtensions/commit/b8eac00ac20ac6740be745e20d99b0f8d904caac

Hope it works and doesn't mess anyone elses code
