### ISSUE TITLE
Switch Extensions

### ISSUE THREAD

**Issue by lfarah** [goktugyil/EZSwiftExtensions#120]
I'd like the ```UISwitch``` to have a ```.toggle()``` just like *Booleans* have a ```.toggle()```, so:
``` swift
var myBool: Bool = true // True
myBool.toggle() // False
```

``` swift
var mySwitch: UISwitch = UISwitch(x: 0, y: 0, w: 50, h: 50)
mySwitch.setOn(true, animated: true) // True
mySwitch.toggle() //False
```

**Comment by goktugyil** [comment]
Good idea, add it 😁

**Comment by goktugyil** [comment]
https://github.com/goktugyil/EZSwiftExtensions/commit/37d23a34086830f9609e717975f35854fe7b1990

**Comment by goktugyil** [comment]
dont forget public
