### ISSUE TITLE
Add methods and properties for NSDate

### ISSUE THREAD

**Issue by N1c0L4z3R** [goktugyil/EZSwiftExtensions#134]
I think there should be a bit more methods and properties for NSDate. First, I know EXSwift had properties for elements such as day, month, year, etc. Those were pretty useful IMO.

Second, I think there should be methods to be able to easily determine if a NSDate is on the same day, same month or same year as another date instead of just having the == operator.

What do you think?

**Comment by N1c0L4z3R** [comment]
By the way, I have done an implementation of some of these methods, I could do a PR if you feel like it would make sense in the library.

**Comment by goktugyil** [comment]
Sounds good, do you use these functions in your own project? If you do send a pull request

**Comment by amosavian** [comment]
the biggest barrier in implementing methods to compare dates in local time differences imo
e.g Now is Jun 6 in Iran while Jun 5 in the US

**Comment by GabrielCartier** [comment]
hey @amosavian I don't think that matters anyway.
The developers should be the one responsible for knowing if they compare dates in different timezones IMO.

**Comment by Yu-w** [comment]
Added a bunch of handy function to NSDate Extension #176

**Comment by lfarah** [comment]
Closed this due inactivity
