### ISSUE TITLE
trimmed() String function behaves unexpected.

### ISSUE THREAD

**Issue by amosavian** [goktugyil/EZSwiftExtensions#137]
trimming string means removing special characters from start and end of string. trim() removes whitespace characters from inside string
e.g:
```
let string = "  Hello how are you   "
let` trimmedStr =  string.trimmed() // = '"Hellohowareyou"
```
While expected result is `"Hello how are you"`

**Comment by goktugyil** [comment]
Thanks, fixed it 👍 

https://github.com/goktugyil/EZSwiftExtensions/commit/609fce34a41f98733f97dfd7b4c23b5d16416206
