### ISSUE TITLE
Can't use on extensions

### ISSUE THREAD

**Issue by GabrielCartier** [goktugyil/EZSwiftExtensions#140]
We are building a keyboard application and we can't use the pod in it. There is a problem with the `UIAlertControllerExtension` class. Here's the error:
`EZSwiftExtensions/Sources/UIAlertControllerExtensions.swift:13:23: 'sharedApplication()' is unavailable: Use view controller based solutions where appropriate instead.`

In my opinion, there should be a different sub pod for extensions that use Application so that we can still use the others in a non-application project.

Thoughts?

**Comment by goktugyil** [comment]
Yes, makes sense. But in that case I guess that shouldn't be the only error you should get. What else are you getting?

If this is the only one, we can tweak it so it works

**Comment by GabrielCartier** [comment]
I can further investigate to know all the errors, let me get back to you on this.

**Comment by goktugyil** [comment]
How is the status of the errors?

**Comment by GabrielCartier** [comment]
Sorry, been a bit busy, didn't have time to get back to you. Project is restarting soon and I'm a bit more free, I got a note to actually update that.

**Comment by lfarah** [comment]
@conradev talks on [this link](https://realm.io/news/altconf-conrad-kramer-writing-iOS-sdk/) about the usage of libraries in Extensions:
![screen shot 2016-09-06 at 12 31 05 am](https://cloud.githubusercontent.com/assets/6511079/18265206/505785e4-73c9-11e6-9ed3-e286e3e8b89e.png)

**Comment by lfarah** [comment]
Hey @GabrielCartier, do you still have problems with this?
If you still need some help, I'll reopen the issue

**Comment by GabrielCartier** [comment]
Sorry, project kind of stopped on this.

I'm working back on it now, I'll try to give it some time and get back to you with some specific things if there are needs!
Thanks!

**Comment by lfarah** [comment]
Thanks!
