### ISSUE TITLE
testFileFunctions() fails on Travis.ci

### ISSUE THREAD

**Issue by lfarah** [goktugyil/EZSwiftExtensions#147]
[Answer 1](http://stackoverflow.com/questions/19309092/nsurl-to-file-path-in-test-bundle-with-xctest)
[Answer 2](http://stackoverflow.com/questions/9157480/nsbundle-pathforresource-returns-nil/24330617#24330617)

**Comment by lfarah** [comment]
@goktugyil can we remove ```testFileFunctions()```?

**Comment by goktugyil** [comment]
https://github.com/goktugyil/EZSwiftExtensions/commit/8902adce50d648181ae2dc8e0dcc9fe405e8ccab

this work?

**Comment by lfarah** [comment]
@goktugyil yeah 🎉
