### ISSUE TITLE
The `addKeyboardWillShowNotification()` and related methods are not type safe

### ISSUE THREAD

**Issue by avismarahl** [goktugyil/EZSwiftExtensions#15]
public func addKeyboardWillShowNotification() {
            self.addNotificationObserver(UIKeyboardWillShowNotification, selector: "keyboardWillShowNotification:");
        }
    
    public func addKeyboardDidShowNotification() {
        self.addNotificationObserver(UIKeyboardDidShowNotification, selector: "keyboardDidShowNotification:");
    }
    
    public func addKeyboardWillHideNotification() {
        self.addNotificationObserver(UIKeyboardWillHideNotification, selector: "keyboardWillHideNotification:");
    }

    
    public func addKeyboardDidHideNotification() {
        self.addNotificationObserver(UIKeyboardDidHideNotification, selector: "keyboardDidHideNotification:");
    }
The above and related methods are  not safe and it might easily cause a crash if the developer is not careful. It's better if we remove it or use a protocol to introduce safety.

**Comment by goktugyil** [comment]
But why did you close this issue after opening it?

**Comment by avismarahl** [comment]
I figured it's not an issue. `addKeyboardWillShowNotification:`  has bee implemented. Will not crash. All though, I am thinking of a better way to achieve this using protocols.

**Comment by goktugyil** [comment]
That would be great, the method is very ugly at the moment
