### ISSUE TITLE
capitalizeFirst should be a method

### ISSUE THREAD

**Issue by lfarah** [goktugyil/EZSwiftExtensions#150]
```capitalizeFirst``` inside ```StringExtensions``` realizes an action of capitalizing the first character of a string, so therefore it should be a method instead of a variable with a getter.

Today's implementation:
``` swift
	/// EZSE: Capitalizes first character of String
	public var capitalizeFirst: String {

		guard characters.count > 0 else { return self }
		var result = self

		result.replaceRange(startIndex...startIndex, with: String(self[startIndex]).capitalizedString)
		return result
	}
```

What it should be:

``` swift
	/// EZSE: Capitalizes first character of String
	public func capitalizeFirst() -> String {

		guard characters.count > 0 else { return self }
		var result = self

		result.replaceRange(startIndex...startIndex, with: String(self[startIndex]).capitalizedString)
		return result
	}
```

**Comment by goktugyil** [comment]
Yes it should, also capitalizeFirst() should change self, while getCapitalizedFirst() or a method like that should return a new string with the first letter capitalized
