### ISSUE TITLE
Add storyboard support for BlockButton

### ISSUE THREAD

**Issue by bigdeer2016** [goktugyil/EZSwiftExtensions#161]
I can't print when i use addAction method

Here's the code:
```
button.addAction { (sender) in
            print("press")
        }
```
why ?

**Comment by piv199** [comment]
Well, I've researched a bit and found next:
This called when you create a block button in code
 ```
   public init(frame: CGRect, action: BlockButtonAction) {
        super.init(frame: frame)
        self.action = action
        defaultInit()
    }
```

This is executed when you create a block button in storyboard
```
    public required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
```

There is no defaultInit() for Storyboard block button. So there is no observer for pressed and highlight events of the button.

Should we add support for Storyboard BlockButton?

**Comment by lfarah** [comment]
@piv199 that should definitely be added. Can you do that, @piv199 ?

**Comment by goktugyil** [comment]
Noob mistake 😞
