### ISSUE TITLE
Load View/ViewController from Nib file

### ISSUE THREAD

**Issue by piv199** [goktugyil/EZSwiftExtensions#162]
Now it looks like the following

`let filterHeaderView = UINib(nibName: FilterHeaderView.className, bundle: nil).instantiateWithOwner(self, options: nil).last as? FilterHeaderView`

Not as Swifty as it could be. Should we have an extension for that?

Well I don't actually know yet how it could be more swifty. Could anybody give an example? Something like `let filterHeaderView = UINib.instantiate(view: FilterHeaderView)` - loads nib from nil bundle with class name name, searches for view with passed class and returns it. Or something more controllable.

**Comment by goktugyil** [comment]
What else needs to be controlled?

**Comment by piv199** [comment]
Just found that we already have something similar in EZSwiftExtensions.

`let view: CustomView = NSBundle.loadNib("nibName")` or let view =` NSBundle.loadNib("nibName") as? CustomView`

However it's a bit confusing as I suppose. Also it's not SwiftLint compliant.

We should control View/ViewController that will be instantiated by its type, nib should also have the same name, thus it's good practice to have the same name for View class and it's xib.

Hm... for ViewController it's not the best approach to always name xib the same as class name. So, perhaps, we should control nib name, class to look up and overloaded owner with owner.

**Comment by goktugyil** [comment]
Yeah, makes sense, personally I don't use storyboards/xibs so you 2 decide

**Comment by lfarah** [comment]
@piv199 how would you do it? I agree with you 100%

Wanna send your *Swiftier* version of this?
``` swift
let view: CustomView = NSBundle.loadNib("nibName") or let view =NSBundle.loadNib("nibName") as? CustomView
```

**Comment by lfarah** [comment]
@piv199 any updates on this? Let me know if you need help! 😉

**Comment by vilapuigvila** [comment]
I have this extension for that:
    public class func fromNib<T : UIViewController>() -> T {
        return T(nibName:String(describing: T.self), bundle: nil)
    }
and then you use:
let vc:SplashViewController = .fromNib()

**Comment by lfarah** [comment]
@piv199 what do you think?

**Comment by vilapuigvila** [comment]
then I create a manager first:
enum ViewControllersManager {
    /// Add more cases
    case splashVC
    case loginVC
    case signupVC
}

then ..
extension ViewControllersManager: RawRepresentable {
    typealias RawValue = UIViewController
    var rawValue: RawValue {
        switch self {
            case .splashVC:      let vc:SplashViewController      = .fromNib()
        return vc
            case .loginVC:       let vc:LoginViewController       = .fromNib()
        return vc
            case .signupVC:      let vc:SignupViewController      = .fromNib()
    }
}

use ViewControllersManager.loginVC.rawValue

**Comment by piv199** [comment]
`let vc = LoginViewController.fromNib()`

Hm.. makes sense... Also, have something like

`let vc = LoginViewController.fromNib(named: "Login")`
`let vc = LoginViewController.fromNib(named: "LoginViewController", bundle: Bundle.self)`

@lfarah As for me, I like this 👍

**Comment by vilapuigvila** [comment]
@piv199 @lfarah  how about that?
    class func fromNib<T:UIViewController>(type: T.Type) -> T {
        return T(nibName:T.self.className, bundle: nil)
    }

and then:
let vc = SplashViewController.fromNib(type: SplashViewController.self)

**Comment by piv199** [comment]
@vilapuigvila 

`let vc = SplashViewController.fromNib(type: SplashViewController.self)`
why not  `let vc = SplashViewController.fromNib()`, if we already have T in function ?

**Comment by vilapuigvila** [comment]
I don't be able to get Type of UIVIewContreller inside function, any ideas?
Thanks
