### ISSUE TITLE
isOnlyEmptySpacesAndNewLineCharacters() 39characters lengths

### ISSUE THREAD

**Issue by piv199** [goktugyil/EZSwiftExtensions#166]
Just for testing string for not containing any useful information we need to call a 39-length method. Also I suggest to make it computable property instead of method.

Should we rename it to something like `isWhitespaced` 
or
`isSpaced` (python-alike)
`isStripped`(python-alike)
`isBlank` (Java-alike)

**Comment by goktugyil** [comment]
I like is blank. Does this method give a warning or anything? I have no problem writing it cause of auto complete atm. If I start to type empty space, or new line, I just get the proper method.

**Comment by piv199** [comment]
@goktugyil yes, but it looks ugly

```
if str1.isOnlyEmptySpacesAndNewLineCharacters() 
   && str2.isOnlyEmptySpacesAndNewLineCharacters() {
    // 
}
```

Well, I'm for that if it's short enough than it's good, otherwise it's bad.
So we could make a method isBlank and leave isOnlyEmptySpacesAndNewLineCharacters() if someone wants to use such long method name.

**Comment by goktugyil** [comment]
You convinced me, go ahead.
