### ISSUE TITLE
Better UIImage resizing

### ISSUE THREAD

**Issue by lfarah** [goktugyil/EZSwiftExtensions#169]
Nowadays, to resize an UIImage, we gotta use this:
``` swift
let image = UIImage(named: "img")
let image2 = UIImage.scaleTo(image: image, w: 50, h: 50)
```
In the example above, we're creating another UIImage from our UIImage, which is kinda confusing. In my opinion, we can make it better:
``` swift
let image = UIImage(named: "img")
image.scaleTo(w: 50, h: 50)
```

What do you guys think? 🤔

**Comment by goktugyil** [comment]
Possibly scaling a current uiimage might have some issues with it, need to double check that

**Comment by piv199** [comment]
@lfarah well, you shouldn't change the object if it marked as let. but maybe it should have two methods - 1 for changing the object, and for returning new one.

**Comment by lfarah** [comment]
@piv199 makes sense. Maybe we should leave it as it is for now....
