### ISSUE TITLE
Slack/Gitter

### ISSUE THREAD

**Issue by piv199** [goktugyil/EZSwiftExtensions#178]
Hi, I just thought whether it would be great to have Slack/Gitter so we could simplify communication of developing, improving this library.

Well, I suppose this will involve some new people to help improve library. 

Maybe, just give a try. What do you think? Thumbs up/down, please :)

**Comment by lfarah** [comment]
[Gitter](https://gitter.im/) is also used a lot for open source libraries' communication

**Comment by goktugyil** [comment]
https://gitter.im/EZSwiftExtensions/Lobby
here it is
