### ISSUE TITLE
Stop adding new features, start adding more tests!

### ISSUE THREAD

**Issue by goktugyil** [goktugyil/EZSwiftExtensions#183]
This is our test coverage at the moment. [Test Coverage](http://image.prntscr.com/image/8641005c999b4698a3dafcff8d8ac73a.png) 

At this point, stability and optimization is more important than new features. So if you want to contribute:
- Copy the real life scenarios in readme.md into unit tests or vice versa (Very easy and beginner friendly)
- Add new tests to uncovered methods
- Optimize speed/syntax/document/version compatibility of current methods

I will be creating empty test files for everything so it will be easy to fill in. Ideally if a user wants to know what a function does, they should be able to just check the tests files and understand from the example code in there.

Thank you all for contributing!

**Comment by lfarah** [comment]
We should use [Danger](http://danger.systems/) to automatically fail a pull request if it doesn't include tests, as well as a bunch of other stuff

**Comment by lfarah** [comment]
So if you can create all the testing files, we can start opening issues for everything that is missing

**Comment by goktugyil** [comment]
Testing files are ready. Just needs to be filled, so thats like 40 issues. I'd rather people choose one file at a time and write tests for it, send a pull request than start working on another file. Kind of like  how piv199 is doing

**Comment by lfarah** [comment]
@goktugyil can we close this? We're about to hit 40% coverage

**Comment by goktugyil** [comment]
40%? Thats still too low :(

**Comment by lfarah** [comment]
@goktugyil I agree, but 40% is good enough for it to stop being our main focus.
The title of this issue is "Stop adding new features, start adding more tests!"
