### ISSUE TITLE
Document the code

### ISSUE THREAD

**Issue by avismarahl** [goktugyil/EZSwiftExtensions#19]
Most of the code seems un-documented. We should add an appledoc style documentation.

**Comment by goktugyil** [comment]
Yeah, its definitely needed. There is a good extension which helps with documentation. I can start doing it from smaller files and people might contribute as they find time?

**Comment by avismarahl** [comment]
VVDocumenter, isn't it? Yup, will contribute as I get tim.

**Comment by goktugyil** [comment]
Yeah thats its.

**Comment by goktugyil** [comment]
It seems VVDocumenter isn't needed, shorter documentation is better. I did the first one:

"EZSE:" is just there to clearly identify from UIKit

https://github.com/goktugyil/EZSwiftExtensions/commit/c8ed6e3a6fbd5e18d494767a49b25fce922b2ae6
https://github.com/goktugyil/EZSwiftExtensions/commit/9dfdbd8f4db4426f09254d8782f04400e29be2a4

**Comment by lfarah** [comment]
Im working on that too!
