### ISSUE TITLE
Swift 3 Support on the way?

### ISSUE THREAD

**Issue by NemOry** [goktugyil/EZSwiftExtensions#191]
Hi guys... I can't wait when you will support Swift 3. I've upgraded to XCode 8 already.. Hope that the update is very soon :) thanks for the great library

**Comment by lfarah** [comment]
Hey @NemOry, [we already have a Swift 3 branch](https://github.com/goktugyil/EZSwiftExtensions/tree/Swift3)

**Comment by chlela** [comment]
@lfarah I've installed the branch through cocoapods  `pod 'EZSwiftExtensions', :git => 'https://github.com/goktugyil/EZSwiftExtensions', :branch => 'Swift3'` and I'm still getting compile errors. What am I missing?

**Comment by lfarah** [comment]
I pushed Swift 3 branch with a few errors I couldn't solve. @goktugyil said he'd take a look and fix them
