### ISSUE TITLE
Don't override existing methods like forEach!

### ISSUE THREAD

**Issue by Sweeper777** [goktugyil/EZSwiftExtensions#195]
I just updated the pod to version 1.6 and found that there is a new `forEach` method. This method name clashes with the existing `forEach` which takes the following signature:

    public func forEach(@noescape body: (Self.Generator.Element) throws -> Void) rethrows

while the EZSE version has this signature:

    public func forEach(call: (Int, Element) -> ())

This breaks a lot of my existing code. Can you rename your `forEach` to something like `forEachWithIndex` or `forEachIndex`?

**Comment by lfarah** [comment]
@Sweeper777, @adhiravishankar is working on a fixed version. After he fixes that, I'll be able to make those changes

**Comment by Sweeper777** [comment]
Thanks!

**Comment by piv199** [comment]
for in with indexes in Swift 3.0 looks like:
```
for (index, element) in list.enumerated() {
  print("Item \(index): \(element)")
}
```

So, possibly, `forEachEnumerated`, `forEnumerated`?

**Comment by Sweeper777** [comment]
I would prefer the former.

**Comment by goktugyil** [comment]
piv199 13 hours ago
Must be renamed e.g. to forEachEnumerated due to collision

**Comment by goktugyil** [comment]
https://github.com/goktugyil/EZSwiftExtensions/commit/a6aed390f01aa5f9c685566636b2c86251a30078

This is what we wanted right?
