### ISSUE TITLE
Type safety hole 

### ISSUE THREAD

**Issue by avismarahl** [goktugyil/EZSwiftExtensions#20]
```swift
public mutating func removeObject<U: Equatable>(object: U) {
    for i in (0..<count).reverse() {
        if let obj = self[i] as? U where obj == object {
            self.removeAtIndex(i)
         }
     }
}
```

The above method seems to have a type safety hole at  `obj = self[i] as? U`, which by the way, should have been ` obj = self[i] as! U` in previous versions of Swift . The API is available for arrays that are not equatable as well. This is unsafe and prone to confusion and error. Also, no exceptions are thrown if the element isn't found. 

We should refactor this to:
```swift
extension Array where Element : Equatable {
    public mutating func removeObject(object: Element) throws  {
        var index = 0
        for element in self {
            if object == element {
                self.removeAtIndex(index)
                return
            }
            index += 1
        }
        throw ArrayException.ObjectNotFound
     }
}
```
where `ArrayException` is
```swift
enum ArrayException : ErrorType {
    case ObjectNotFound
}
```
This is just an example we should apply this to all places where we are conditionally/forcefully downcasting to a type constraint.

**Comment by goktugyil** [comment]
Good catch. I'm logging off now, I'll check this the next time I sit down.

**Comment by avismarahl** [comment]
Shall I start working on this?

**Comment by goktugyil** [comment]
Yeah man, sorry I couldn't find time to look at this yet

**Comment by arielpollack** [comment]
even better:
```
extension Array where Element: Equatable {
    mutating func removeElement(element: Element) {
        if let index = self.indexOf(element) {
            self.removeAtIndex(index)
        } else {
            // raise exception
        }
    }
}
```
