### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by v-silin** [goktugyil/EZSwiftExtensions#204]
Hi.

Do you have any plans about swift 3?

Best regards.

**Comment by lfarah** [comment]
Hey @v-silin, we updated to Swift 3 but we're currently having problems on pushing to CocoaPods. Please use the following:
```  pod 'EZSwiftExtensions', :git => 'https://github.com/goktugyil/EZSwiftExtensions.git'```

Let me know if you need anything else! 😉

**Comment by v-silin** [comment]
Cool! Thank you!)

**Comment by goktugyil** [comment]
Sorry for the delay, just released a stable version for Swift 3.0

```ruby
platform :ios, '8.0'
use_frameworks!
pod 'EZSwiftExtensions' #Stable release for Swift 3.0

pod 'EZSwiftExtensions', :git => 'https://github.com/goktugyil/EZSwiftExtensions.git' #Latest release for Swift 3.0
pod 'EZSwiftExtensions', :git => 'https://github.com/goktugyil/EZSwiftExtensions.git', :branch => 'Swift2.3' #For Swift 2.3
pod 'EZSwiftExtensions', '~> 1.6' #For Swift 2.2
```

**Comment by matthew-reilly** [comment]
Seems like the 1.6 version for Swift 2.2 is broken. Getting ~3000 errors on build. :/

**Comment by goktugyil** [comment]
@matthew-reilly I'm using 1.6 and have been using it for 2 months. It is working properly. Are you using Xcode8? Or Maybe Swift2.3?
