### ISSUE TITLE
Swift3StrikesBack: NSDateTests

### ISSUE THREAD

**Issue by goktugyil** [goktugyil/EZSwiftExtensions#207]
NSDateTests

`fileprivate func < <T : Comparable>(lhs: T?, rhs: T?) -> Bool {
`
Should be removed. The method below is using that part. If we really need this "<", and it seems useful, lets add it to NSDateExtensions, in that case the tests should not test using another extension.

```
    func testComparable() {
        let date = Date()
        let future = Date(timeIntervalSinceNow: 1000)
        XCTAssertTrue(date < future)
        XCTAssertFalse(date > future)
        XCTAssertTrue(date == date)
    }
```

**Comment by goktugyil** [comment]
```
extension NSDate: Comparable {}
 /// EZSE: Returns if dates are equal to each other
public func == (lhs: NSDate, rhs: NSDate) -> Bool {
  return lhs.isEqualToDate(rhs)
}
 /// EZSE: Returns if one date is smaller than the other
public func < (lhs: NSDate, rhs: NSDate) -> Bool {
    return lhs.compare(rhs) == .OrderedAscending
}

public func > (lhs: NSDate, rhs: NSDate) -> Bool {
  return lhs.compare(rhs) == .OrderedDescending
}
```
Apple stealing our extensions 👍

**Comment by goktugyil** [comment]
https://github.com/goktugyil/EZSwiftExtensions/commit/5572c5cbccfaeaceead4be4282097349be5b9ce7

**Comment by piv199** [comment]
It's not NSDate dependent, it's generics. It can compare everything that could be nil or not.

let a: Int? = 5
let b: Int? = nil

a < b //false

**Comment by goktugyil** [comment]
Thats even better
