### ISSUE TITLE
[Question] Add UnderscoreJS and Lodash type support?

### ISSUE THREAD

**Issue by fbuentello** [goktugyil/EZSwiftExtensions#21]
Before I start implementing or creating a pull request, I wanted to ask if [UnderscoreJS](http://underscorejs.org/) and [Lodash](https://lodash.com/) would be appropriate extensions to include in this Library? Here is an example of these type of Extensions already implemented in Swift, [**Dollar.swift**](https://github.com/ankurp/Dollar.swift).

**Comment by goktugyil** [comment]
Some of the functionality there seem good. But the implementation should be swift-like. Except for the file "ez" which includes popular global stuff, all the extensions must feel natural.

**Comment by thellimist** [comment]
The most useful function from _ are already implemented in Swift 2.0 by default. Did you encounter any functions provided by _ which are hard to do in swift?

**Comment by goktugyil** [comment]
I'm closing this if there is nothing else to add
