### ISSUE TITLE
Swift3 Documentation Comments

### ISSUE THREAD

**Issue by goktugyil** [goktugyil/EZSwiftExtensions#211]
```
///Explanation of dosomething
func doSomething() {

}
```

The comment is not showing up on auto complete, what is the problem?

**Comment by piv199** [comment]
Maybe because Apple implemented HeaderDoc in Xcode 8?

Select method and press Option+Command+/

It will generate /* */ header doc comment

**Comment by goktugyil** [comment]
No it created a /// header doc comment

**Comment by piv199** [comment]
@goktugyil yeah, that's strange. Need more investigation...

**Comment by lfarah** [comment]
This is an Xcode bug. @goktugyil wanna open a radar?
If you right click the method, the documentation still shows up, so it's not any problem on our lib.

<img width="501" alt="screen shot 2016-10-26 at 2 27 44 pm" src="https://cloud.githubusercontent.com/assets/6511079/19745849/6a0fca0a-9b88-11e6-9007-7a63937b1d3a.png">

**Comment by goktugyil** [comment]
Yeah Xcode bug.. Nothing we can do except radar.
