### ISSUE TITLE
Add Danger.systems

### ISSUE THREAD

**Issue by lfarah** [goktugyil/EZSwiftExtensions#221]
We should use [Danger](http://danger.systems/) to automatically fail a pull request if it doesn't include tests, as well as a bunch of other stuff.

**Comment by piv199** [comment]
@lfarah https://github.com/fastlane/fastlane/blob/master/Dangerfile

as example

**Comment by goktugyil** [comment]
Done?

**Comment by lfarah** [comment]
Yup.
