### ISSUE TITLE
hideKeyboardWhenTappedAround Cant tap on cell

### ISSUE THREAD

**Issue by Xopoko** [goktugyil/EZSwiftExtensions#230]
After add this method to viewDidLoad, i cant tap to my tableView cell. Long tap highlights cell, but didTap not working. Superclass is UIViewController.

**Comment by lfarah** [comment]
@Xopoko Are you using Xcode 8?

**Comment by Xopoko** [comment]
@lfarah Yes

**Comment by furuyan** [comment]
@Xopoko 
Maybe this issue is same as this
http://stackoverflow.com/questions/8192480/uitapgesturerecognizer-breaks-uitableview-didselectrowatindexpath

**Comment by goktugyil** [comment]
Oh here in the comments of my answer a lot of people talked about this issue:
http://stackoverflow.com/questions/24126678/close-ios-keyboard-by-touching-anywhere-using-swift/27079103#27079103
