### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [goktugyil/EZSwiftExtensions#239]
Is this upgraded to swift 3?

If yes, what is to be write inside Podfile in order to download?

**Comment by lfarah** [comment]
Hey @Rashesh-Bosamiya, EZSwiftExtensions is compatible with Swift 3.
Please add the following to your Podfile:
``` ruby
pod 'EZSwiftExtensions', '1.7'
```

Let me know if you have any other questions! 😉
