### ISSUE TITLE
How to get the keyboard height

### ISSUE THREAD

**Issue by rx2130** [goktugyil/EZSwiftExtensions#267]
I was able to add and move notification related to keyboard show/hide cycle. But when I tried to override `keyboardWillShowWithFrame`, it shows an error **overriding non-open instance method of its defining module**. 

So I tried to change the source code `keyboardWillShowWithFrame` from `public` to `open` to be able to override it. But yet it still complains the same error. Can you let me know the proper way to use this extension?

**Comment by piv199** [comment]
@rx2130 I think extension should also be marked open?

**Comment by piv199** [comment]
The bug itself mentioned in #205

**Comment by piv199** [comment]
The bug itself mentioned in #205
