### ISSUE TITLE
UIColoredView

### ISSUE THREAD

**Issue by lfarah** [goktugyil/EZSwiftExtensions#270]
Today we have an `UIColoredView.swift`, that returns a 100x100 `UIView` with a random `UIColor`.

@goktugyil created this and I'd like to question if it is really necessary for **EZSwiftExtensions** since I don't see many use cases for this, especially because we already have extensions that already make it easy to do it:

``` swift
let view = UIView(x:0,y:0,w:100,h:100)
view.backgroundColor = UIColor.randomColor()
```

**Comment by lfarah** [comment]
@goktugyil?

**Comment by goktugyil** [comment]
Nope, its not necessary. Helped a bunch while testing some stuff, but its not helping a lot and not used alot, so we can delete it.
