### ISSUE TITLE
NSDictionary Tests

### ISSUE THREAD

**Issue by lfarah** [goktugyil/EZSwiftExtensions#281]
We have a problem on ```NSDictionaryExtensions.swift``` test coverage.

#### NSDictionaryExtensionTests
``` swift
class NSDictionaryTests: XCTestCase {
    
    func testDicToJSON() {
        let dic: NSDictionary = ["foo":"bar"]
        let json = dic.formatJSON()
        let str = "{\"foo\":\"bar\"}"
        XCTAssertEqual(json, str)
    }
    
    func testJSONtoDic() {
        
        let str = "{\"foo\":\"bar\"}"
        let dic = NSDictionary(json: str)
        let dicExpected: NSDictionary = ["foo":"bar"]
        XCTAssertEqual(dic, dicExpected)
    }
}
```

#### Coverage
<img width="876" alt="screen shot 2016-10-30 at 10 29 45 pm" src="https://cloud.githubusercontent.com/assets/6511079/19845070/8fe7cdf2-9ef0-11e6-867a-f8db1428f753.png">

**Comment by piv199** [comment]
Hm, what it could be?

**Comment by lfarah** [comment]
@piv199 I'm thinking about it now... Should we have NSDictionaryExtensions at all? [Ray Wenderlich's Style Guide](https://github.com/raywenderlich/swift-style-guide#types) says this:
## Types

Always use Swift's native types when available. Swift offers bridging to Objective-C so you can still use the full set of methods as needed.

**Preferred:**
```swift
let width = 120.0                                    // Double
let widthString = (width as NSNumber).stringValue    // String
```

**Not Preferred:**
```swift
let width: NSNumber = 120.0                          // NSNumber
let widthString: NSString = width.stringValue        // NSString

**Comment by lfarah** [comment]
@goktugyil ?

**Comment by goktugyil** [comment]
Whats the problem, I don't get it?

Changing this to standard Dictionary would work the same right? If it does no problem in changing it

**Comment by lfarah** [comment]
@piv199 what do you think?

**Comment by piv199** [comment]
@lfarah I agree with @goktugyil, change everything to Dictionary 👍
