### ISSUE TITLE
Some file names should drop NS Prefix

### ISSUE THREAD

**Issue by furuyan** [goktugyil/EZSwiftExtensions#285]
Some file names and implementations isn't match.
e.g.
```
NSDateExtensions.swift
extension Date {
```

So i think we should rename some files.

Target is below.

- NSBundleExtensions.swift
- NSDateExtensions.swift
- NSUserDefaultsExtension.swift
- NSTimerExtensions.swift
- NSURLExtensions.swift
- each test file

**Comment by lfarah** [comment]
Thanks for pointing that out! I always saw that but never remembered to open an issue.
@goktugyil: we need to come up with a way that doesn't break everybody's projects

**Comment by piv199** [comment]
@lfarah we just can rename files and it will not break projects at least which uses cocoapods/carthage.

P.S. the same. I always see, but always forget :)

**Comment by lfarah** [comment]
@piv199 but we still need to rename the classes and that will definitely break a looot of things

**Comment by piv199** [comment]
@lfarah What classes are you gonna rename that will break compatibility?

**Comment by lfarah** [comment]
@piv199 it's not compatibility, but if people were using... hmmm thinking about it, it really doesn't matter because in Xcode 8 the compiler won't let you use, for example, ```NSTimer```. Even if we currently have ```NSTimerExtensions```, they already work on the ```Timer``` class.
Summarizing my thoughts: true, it won't break anything

**Comment by goktugyil** [comment]
So the compiler will think we're extending NSTimer whether we extend NSTimer or Timer?

**Comment by Khalian** [comment]
IIRC the NS namespace is a legacy and is no hurry to be replaced. 

In my opinion the since files are not exposed to the consumer it does not make any difference to the end user. 

e.g no one would use import NSBundleExtensions

Moreover if the underlying data type retains the NS prefix, it will end up confusing contributors on what exactly is being extended.

**Comment by lfarah** [comment]
@goktugyil do you wanna open a PR since it involves file changing?

**Comment by goktugyil** [comment]
Sure

**Comment by goktugyil** [comment]
Forgot to open a branch, oh well.

https://github.com/goktugyil/EZSwiftExtensions/commit/f489f13e8caeecfb6a1437ed8f95f702d86bb342
https://github.com/goktugyil/EZSwiftExtensions/commit/fe49760a56eba0559f85f4c8a626bbd32af355a0
https://github.com/goktugyil/EZSwiftExtensions/commit/545280584f827b84d4dce65b3061ce2e4dde58e8
https://github.com/goktugyil/EZSwiftExtensions/commit/cece3c172ac9bc872bbd6b9e30a2bfbdafe5bf6d
https://github.com/goktugyil/EZSwiftExtensions/commit/4ec595a5575921737dfa8f5b032a9bc20be08273
https://github.com/goktugyil/EZSwiftExtensions/commit/c568edecf1b83852e31b4cd05336f9d06ca0c27e

**Comment by goktugyil** [comment]
Thanks @furuyan

**Comment by goktugyil** [comment]
We can possibly change nsurls in url file to no prefix urls, not sure if those would break anything or not.
