### ISSUE TITLE
Should we have a waffle board for tasking?

### ISSUE THREAD

**Issue by Khalian** [goktugyil/EZSwiftExtensions#288]
https://waffle.io/

Or are github issues sufficient?

**Comment by lfarah** [comment]
I think Github issues are enough since we are an Open Source library.

**Comment by piv199** [comment]
@Khalian We could use Github Projects, can't we?

**Comment by Khalian** [comment]
@piv199 Yea we can.

I meant for the sake of organizing non trivial tasks.
