### ISSUE TITLE
I can't push a new branch.

### ISSUE THREAD

**Issue by vilapuigvila** [goktugyil/EZSwiftExtensions#297]
Hi everyone!
I'd like to contribute to this repo and today I've not been able to push my branch, I got this message:
remote: Permission to goktugyil/EZSwiftExtensions.git denied to vilapuigvila.
fatal: unable to access 'https://github.com/goktugyil/EZSwiftExtensions.git/': The requested URL returned error: 403
Thanks in advance.

**Comment by lfarah** [comment]
Hey @vilapuigvila, I'm glad you want to contribute. Every help is always welcome.
In order to send a contribution, you will have to fork the repository and then send a Pull request from your branch in your fork to the master in EZSwiftExtensions.

If you need help, I'm here for you! 😃 👍

**Comment by Khalian** [comment]
Hi @vilapuigvila. So you need to be on a collaborator status to publish to public repositories. 

Try forking this repo, make changes there are use the Github pull request feature for people to review your changes. Once you get approvals (after review process is over), a collaborator will merge the changes into mainline. 

Hope this helps.

**Comment by vilapuigvila** [comment]
Hi @lfarah @Khalian thanks for your fast awsers. Perfect I'm going to try  to do it.
Thanks
