### ISSUE TITLE
Accessing app delegate

### ISSUE THREAD

**Issue by fastred** [goktugyil/EZSwiftExtensions#3]
Hi,

Making app delegate easier to access won't lead to better code, because that pattern leads to circular dependencies. Please consider removing this part.

Good job on other parts of the library!

Thanks!

**Comment by goktugyil** [comment]
Hello, thanks for feedback, I see the problem. Do you think there is a way to modify this without removing this functionality?

**Comment by goktugyil** [comment]
Couldn't find anyway, so deleted it. Thanks

**Comment by fastred** [comment]
Sorry, I didn't get an email notification when you answered. Thanks for removing it!
