### ISSUE TITLE
module compiled with swift 3.0 cannot be imported in swift 3.0.1

### ISSUE THREAD

**Issue by HuaZao** [goktugyil/EZSwiftExtensions#317]
How should I solve this error? I use Carthage  import  EZSwiftExtensions

**Comment by HuaZao** [comment]
![image](https://cloud.githubusercontent.com/assets/13476604/20415993/dc108928-ad76-11e6-89f7-48662ca1e235.png)

**Comment by lfarah** [comment]
Hey @HuaZao, I don't personally use Carthage, but I'll do my best on finding someone to help you on this!

**Comment by furuyan** [comment]
@HuaZao 
This error is due to framework that is built by old Swift version (Swift3.0).
So you should rebuild framework with latest Swift version (Swift3.0.1).
Would you execute following command?
```
carthage bootstrap --platform iOS --no-use-binaries
```

**Comment by Khalian** [comment]
Interesting, I wasnt aware that swift compilers are not backwards compatible across minor versions.

**Comment by furuyan** [comment]
Swift 3.0 not having ABI(Application Binary Interface) compatibility.
https://github.com/apple/swift-evolution/commit/06b69a6e51a71a462c268da60b51a18966dba31b

**Comment by gautier-gdx** [comment]
You need to tell Carthage not to use the build provided: carthage update --platform iOS --no-use-binaries     
with this you will compile the framework on your computer automatically with your current version of Swift

**Comment by Khalian** [comment]
Should we document this in the Readme.

**Comment by furuyan** [comment]
I think it doesn't need.
Because it's not a general case.
