### ISSUE TITLE
NSDate.tostring() not working as expected

### ISSUE THREAD

**Issue by goktugyil** [goktugyil/EZSwiftExtensions#33]
https://github.com/goktugyil/EZSwiftExtensions/commit/fe7c2bffa4ac152a6a5e9ee02e307d7b046c6cdc
https://github.com/goktugyil/EZSwiftExtensions/commit/30a8f793a23a6b46e86b549ccbb4c3f379690119

I am trying to use this example and I run this code and get the following results:

        let format = "yyyy/MM/dd"
        let fromString = "2016/01/11"
        var date = NSDate(fromString: fromString, format: format)
        print(date) // Optional("2016/01/11 00:00:00 +0000")
        print(date?.toString())

Optional(2016-01-11 08:00:00 +0000)
Optional("12:00:00 AM")

I think toString() should include the whole date. 
@furuyan

**Comment by furuyan** [comment]
Thanks for pointing it out.
I think so too.
Add two method below.
```
let format = "yyyy/MM/dd"
let fromString = "2016/01/11"
let date = NSDate(fromString: fromString, format: format)
print(date?.toString(dateStyle: .MediumStyle, timeStyle: .MediumStyle))
print(date?.toString(format: "yyyy/MM/dd HH:mm:ss"))

results:
Optional("Jan 11, 2016, 12:00:00 AM")
Optional("2016/01/11 00:00:00")
```
