### ISSUE TITLE
Swift 3 Ambiguous use of .month .day .year

### ISSUE THREAD

**Issue by otymartin** [goktugyil/EZSwiftExtensions#353]
These were working well in version 1.7 but version 1.8 spits out error `Ambigous use of....`

```swift
    var dateOfBirth: Date?
     ...
//Date of Birth
    var DOBMonth: Int {
        return (self.dateOfBirth?.month)!
    }
    
    var DOBDay: Int {
        return (self.dateOfBirth?.day)!
    }
    
    var DOBYear: Int {
        return (self.dateOfBirth?.year)!
    }

**Comment by Khalian** [comment]
I tried reproducing your issue. 

let dateOfBirth = Date()
        print(dateOfBirth.month)
        print(dateOfBirth.day)
        print(dateOfBirth.year)

And I was able to successfully get 

1
2
2017

Which is as expected. Breakpoints revealed the right extensions are called. 

These extensions were added as a part of release v1.8 in PR https://github.com/goktugyil/EZSwiftExtensions/pull/313. 

I suspect you are using extension from a conflicting library prior to your update or writing your own custom extension for the same.

**Comment by otymartin** [comment]
@Khalian Your right, it was conflicting with [SwiftDate](https://github.com/malcommac/SwiftDate)

**Comment by Khalian** [comment]
Ok. I suspected as such. 

We made many additions to Date. You can refer to them in https://github.com/goktugyil/EZSwiftExtensions/blob/master/CHANGELOG.md. If they cover your all your use cases, you can remove the dependency from SwiftDate and consume EZSwiftExtensions exclusively.

**Comment by otymartin** [comment]
@Khalian Yea I must just go that route. Thanks

**Comment by Khalian** [comment]
@otymartin No problem happy to help.
