### ISSUE TITLE
UIImage.base64

### ISSUE THREAD

**Issue by lfarah** [goktugyil/EZSwiftExtensions#355]
Nowadays we have an extension that initializes an ```UIImage``` from a base64 String, but we don't have a way to easily convert an UIImage to base64

I'm currently in a project so I don't have time to open the PR. Will do it tomorrow
``` swift
extension UIImage {
    
    var base64: String {
        
        let data = UIImageJPEGRepresentation(self, 1.0)
        return data!.base64EncodedString()
    }
}
```

**Comment by Khalian** [comment]
Just return UIImageJPEGRepresentation(self, 1.0).base64EncodedString(). The let is superflous.
