### ISSUE TITLE
String extesion to get image

### ISSUE THREAD

**Issue by vilapuigvila** [goktugyil/EZSwiftExtensions#357]
What do you think?
extension String {
    public func fetchImage() -> UIImage? {
        guard let image = UIImage(named:self) else {
            return nil
        }
        return image
    }
}

let image = "someImage".fetchImage

**Comment by piv199** [comment]
I personally not recommend to use any String related stuff with Images, segues, reuseIdentifiers and so on. It's dangerous!

**Comment by vilapuigvila** [comment]
and how do you manage segues, reuse Identifiers,  etc..?

**Comment by piv199** [comment]
@vilapuigvila I use R.swift

**Comment by Khalian** [comment]
Yea I dont think there is any purpose to tie down UIImage to String extensions. UIImage is from UIKit which requires this method to be compiled with an #ios preprocessor around it. If anything this method might be suitable in extension UIImage.

**Comment by lfarah** [comment]
I also do not recommend using that. We already have [this extension](https://github.com/goktugyil/EZSwiftExtensions/blob/master/Sources/UIImageExtensions.swift#L109) that works pretty well
