### ISSUE TITLE
Discussions about applying to apache incubator status

### ISSUE THREAD

**Issue by Khalian** [goktugyil/EZSwiftExtensions#359]
http://incubator.apache.org/

@goktugyil @lfarah @piv199 Thoughts on the same ?

**Comment by goktugyil** [comment]
Looks interesting. But its not clear what concrete value would they provide?

**Comment by Khalian** [comment]
Well fame and traction for one (being either incubator or top level status in the ASF is a pretty big deal). 

We have to switch to apache v2.0 license.

**Comment by lfarah** [comment]
I'm down for it. We could schedule a Skype call to discuss it

**Comment by Khalian** [comment]
Sure, whenever all the maintainers agree on a time.

**Comment by lfarah** [comment]
Any weekday from 1pm - 2am (GMT-2) is perfect for me!

**Comment by Khalian** [comment]
So it solves the following problems

1. It enforces the meritocracy that we have agreed to on this forum instead of holding to a nucleus member (e.g Linus Torvalds of the linux foundation). This ensures with a certain degree of probability that the project does not die out if any of us decide to move on to other things. 

2. The apache foundation provides legal and tech support for us (infrastructure if needed, but that is not really a concern for this project). In particular the apache legal support protects us against any form of liabilities. 

3. The biggest benefit is the apache brand. Makes our project seem more legit. 

Of course there are challenges. We have to get a champion for the project from some existing apache top committers and move our licensing to apache instead of MIT (they are both permissive so userspace impact should be minimal).

**Comment by lfarah** [comment]
@goktugyil /\

**Comment by goktugyil** [comment]
3 seems like the biggest benefit. Since the project is fully open source with collaborator permissions I don't see a case where it can die.

How do you find the champion?

**Comment by Khalian** [comment]
@goktugyil I can lurk on the apache mailing lists and request people to take a look at our project. I dont see any other way.

**Comment by goktugyil** [comment]
Sounds simple enough

**Comment by Khalian** [comment]
Cool I will start the leg work and keep you guys posted.

**Comment by goktugyil** [comment]
I wondered what happened with this
