### ISSUE TITLE
Date.iso8601

### ISSUE THREAD

**Issue by lfarah** [goktugyil/EZSwiftExtensions#361]
What do you guys think?
Got it from [this link](http://stackoverflow.com/a/28016614/2938877)

ISO8601 is a representation of dates and times is an international standard covering the exchange of date and time-related data. Many backend services like to use ISO8601, which looks like this:
```1990-01-01T00:00:00```

``` swift
extension Date {
    
    var iso8601: String {
        let formatter = ISO8601DateFormatter()
        return formatter.string(from: self)
    }
}
```

**Comment by Khalian** [comment]
Is this internationalized ? I mean a comment for context pls.

**Comment by lfarah** [comment]
@Khalian better?

**Comment by Khalian** [comment]
I guess this a good idea. The only tricky part would be testing, since we do not know which time zone the travis ci build servers are. I assume we can test some custom dates and their iso8601 counterparts. Otherwise it looks good, I think you can go ahead and submit a PR.

**Comment by Khalian** [comment]
PR in https://github.com/goktugyil/EZSwiftExtensions/pull/375
