### ISSUE TITLE
UIViewController.setBackgroundImage is internal

### ISSUE THREAD

**Issue by lfarah** [goktugyil/EZSwiftExtensions#364]
<img width="883" alt="screen shot 2017-01-13 at 12 33 58 pm" src="https://cloud.githubusercontent.com/assets/6511079/21933457/a3755bce-d98c-11e6-9648-43ea85f9783f.png">

**Comment by Khalian** [comment]
https://github.com/goktugyil/EZSwiftExtensions/pull/367. And I am merging this in without approvals since this is a bug.
