### ISSUE TITLE
Swift Lint errors

### ISSUE THREAD

**Issue by Khalian** [goktugyil/EZSwiftExtensions#370]
https://travis-ci.org/goktugyil/EZSwiftExtensions

I am suddenly witnessing a large number of swift lint issues. Not sure if lint is upgraded in travis CI or not.

**Comment by lfarah** [comment]
[It upgraded in travis](https://github.com/goktugyil/EZSwiftExtensions/blob/master/.travis.yml#L15).
Please run `brew upgrade swiftlint` on your machine to see the new issues.
I'll try to send a PR fixing the issues
