### ISSUE TITLE
roundCorners ruins CollectionView

### ISSUE THREAD

**Issue by otymartin** [goktugyil/EZSwiftExtensions#372]
@goktugyil @Khalian 
I'm using [JSQMessagesViewController](https://github.com/jessesquires/JSQMessagesViewController)

When I use the `self.collectionView?.layer.cornerRadius = 5`. My `collectionView` stays intact however problem is this rounds all four corners. 

<img width="319" alt="screen shot 2017-01-24 at 1 14 11 pm" src="https://cloud.githubusercontent.com/assets/2222881/22260440/41b47d3a-e237-11e6-875a-e6e5b69434fc.png">

So Instead I use the `EZSwiftExtensions` methods...
`let corners = UIRectCorner.topLeft.union(UIRectCorner.topRight)
self.collectionView?.roundCorners(corners, radius: 5)`

This creates a problem where my entire `collectionView` is being dragged around relative to the underlying view when I attempt to scroll the messages in my collectionView.

SCROLL DOWN
<img width="323" alt="screen shot 2017-01-24 at 1 20 11 pm" src="https://cloud.githubusercontent.com/assets/2222881/22260662/006ec442-e238-11e6-978e-711f26ca6240.png">

SCROLL UP
<img width="322" alt="screen shot 2017-01-24 at 1 21 01 pm" src="https://cloud.githubusercontent.com/assets/2222881/22260669/05fff020-e238-11e6-977c-767b24aea9ec.png">

**Comment by lfarah** [comment]
Hey @TimOliver... Do you have any idea why that is happening? I remember that you lib deals with round corners

**Comment by TimOliver** [comment]
Um, I'm not too sure where the 'roundCorners' property of the collection view is coming from, so I can't tell for sure what's happening.

But suffice it to say, setting the cornerRadius of a CALayer will round every corner. There's no way to selectively pick the corners that get rounded.

But you can get around this though by making a separate CALayer and then assigning it as the 'mask' property of that layer: http://stackoverflow.com/questions/10167266/how-to-set-cornerradius-for-only-top-left-and-top-right-corner-of-a-uiview

**Comment by lfarah** [comment]
[It comes from here](https://github.com/goktugyil/EZSwiftExtensions/blob/master/Sources/UIViewExtensions.swift#L561)

**Comment by Khalian** [comment]
This is not really my expertise, @lfarah is there something we can do here ?

**Comment by lfarah** [comment]
I think that that's not something we can implement on EZSwiftExtensions, but @otymartin has to implement @TimOliver's answer on his code.
Closing this, but if there are any other questions, feel free to re-open
