### ISSUE TITLE
Graphs as custom data types

### ISSUE THREAD

**Issue by Khalian** [goktugyil/EZSwiftExtensions#380]
http://waynewbishop.com/swift/graphs/

So this does not directly fit the mandate of extensions, but IMO adjacency lists and adjacency matrices are very common data structures that a lot of programmers reuse all the times.

What do you guys think about introducing basic Graph Data structures in this library?

**Comment by lfarah** [comment]
Definitely makes sense. We'd create new classes? I don't think there's a problem in that since we already have things like the `BlockButton`, for example

**Comment by Khalian** [comment]
Yes it would be new classes.

**Comment by goktugyil** [comment]
Also grid system data type will probably useful. But the problem is it will only be used by a very low % of the users. And some people have a concern about unused features polluting the namespace. 

So we should either think about it a little more or find a way to address this concern.

**Comment by Khalian** [comment]
I would necessarily call it a grid. Its more of a representation for graphs. 

To avoid pollution of namespaces, we can go with prefixing EZ (e.g. EZEdge or EZNode).

**Comment by goktugyil** [comment]
We could also change the Block stuff into easy as well. Also I think it might be possible to implement the functionality of block buttons as extensions with swifts new version, not sure tho.

**Comment by Khalian** [comment]
I am not pushing for this since there isn't a terrific use case that warrants it.
