### ISSUE TITLE
deprecated forEach name collision

### ISSUE THREAD

**Issue by DanielAsher** [goktugyil/EZSwiftExtensions#386]
Hi,
thanks for a great framework!

I'm having a problem that the deprecated `forEach` function is interfering with the standard library. This happens even though I have not added `import EZSwiftExtensions` at the top of the file in which the collision occurs.

This seems to be a general problem of namespace pollution that large extension libraries have. Has there been any discussion of factoring the library to allow limited protocol imports per file?

**Comment by DanielAsher** [comment]
I just follow up the second suggestion with #387

**Comment by Khalian** [comment]
I replied in #387. @DanielAsher Would you mind if I close this thread and discuss on that one directly ?

**Comment by DanielAsher** [comment]
@Khalian - thanks for quick response

Please close - but perhaps simply suggest here a timeline for the removal of the colliding and deprecated methods. I, and perhaps other, are currently unable to use the standard library `forEach`when adding this framework as a target framework.

Cheers

**Comment by lfarah** [comment]
Hey @DanielAsher, I definitely agree that we must find a quick fix for this because I had the same problem as you in a client's project
