### ISSUE TITLE
A shorter release this time?

### ISSUE THREAD

**Issue by Khalian** [goktugyil/EZSwiftExtensions#388]
Our last release took longer. IMO releases should be frequent for OSS projects to formalize recent changes.

We have had some decent set of features of going in till now (not as much as 1.8 though). Would the maintainers be interested in releasing now ?

**Comment by goktugyil** [comment]
Am I the only one who can push a new release? I think at least in cocoapods I'm the only one, but I think I can add other maintainers too. 

@piv199 @lfarah 

Ready for release, agree/disagree?

**Comment by lfarah** [comment]
I also agree we took to long to push a new release. [You can also add us as mainteiners](https://guides.cocoapods.org/making/getting-setup-with-trunk.html)

**Comment by lfarah** [comment]
Just so we're organized, can we [add things to the project](https://github.com/goktugyil/EZSwiftExtensions/projects/1)

**Comment by lfarah** [comment]
@Khalian did I miss anything? If not, please make a PR changing the `CHANGELOG.md``` to `1.9` and add a `1.9` tag, so @goktugyil can push it to CocoaPods

**Comment by Khalian** [comment]
Yeah, that should we about it, I will try to post out the fixes and update the changelog and send a CR. Also tag the release to 1.9.

**Comment by lfarah** [comment]
Perfect. Thanks @Khalian 👍

**Comment by goktugyil** [comment]
@lfarah You have pod access now, you should push 1.9 to learn how things are.

Heres a checklist: https://github.com/thellimist/EZPods

@Khalian @piv199 

I got this error message: 

[!] No owner found with the specified email address.

Its probably because you don't have a library or registered in cocoapods.

**Comment by piv199** [comment]
I haven't been watching for a while, so I can't tell about release :) If it's needed then do.
I wish I could blend in the project asap. I was really missing the open source.

**Comment by goktugyil** [comment]
@lfarah we need a pod release

**Comment by lfarah** [comment]
![screen shot 2017-03-01 at 6 40 51 pm](https://cloud.githubusercontent.com/assets/6511079/23482655/9f21e758-feae-11e6-8eef-baf22df34bfe.png)

![giphy 22](https://cloud.githubusercontent.com/assets/6511079/23482684/ae0860b2-feae-11e6-9339-ff7eec7de657.gif)

**Comment by lfarah** [comment]
@Khalian we have a problem tho: we forgot to update the podspec, so we gotta remove tag 1.9 and add it again since we need to add [this commit](https://github.com/goktugyil/EZSwiftExtensions/commit/7e632cf59d117ba691536a281fc3c572218a00b6)
