### ISSUE TITLE
Array's removeObject only removes the last found.

### ISSUE THREAD

**Issue by gmertk** [goktugyil/EZSwiftExtensions#4]
Hi,

Not clear what is the real intention of this function. To remove the first found, the last found or all of the found objects? Right now it removes only the last one. 

Cheers!

**Comment by goktugyil** [comment]
The intention is when there is only one object of a certain type in an array, removing that object without manually searching its index. 

Removing the last found is a coincidence that wasn't thought of. But it can certainly be changed to remove the first, remove last or all inside.

What was your intended use case?

**Comment by gmertk** [comment]
I would expect `removeObject` to remove all occurrences of a given object (as  `NSMutableArray`'s `removeObject` does).

**Comment by goktugyil** [comment]
Ok, makes sense. Feel free to send a pull request. 

Or I will do it later when I am updating the repo
