### ISSUE TITLE
Precision String Format Specifier

### ISSUE THREAD

**Issue by Alexsmile2010** [goktugyil/EZSwiftExtensions#40]
http://stackoverflow.com/questions/24051314/precision-string-format-specifier-in-swift

**Comment by goktugyil** [comment]
Which extension are you referring about?

**Comment by Alexsmile2010** [comment]
I wanted to tell you to add an extension for double or float  type. If I have value 3.14159265359 but I need 3.14 to display in label for example . Sorry for my English.

**Comment by goktugyil** [comment]
Sure I'll add it in the next update

**Comment by lfarah** [comment]
@Alexsmile2010 now this is possible thanks to #59

**Comment by Alexsmile2010** [comment]
You are the best 😊



С уважением Алексей Заякин.


Четверг, 18 февраля 2016 г., 10:49 +0200 от notifications@github.com  <notifications@github.com>:

**Comment by lfarah** [comment]
Thanks! I'm really working to improve EZSwiftExtensions. Let us know if you have another extension idea!

**Comment by goktugyil** [comment]
@Alexsmile2010 We updated the function like this: https://github.com/goktugyil/EZSwiftExtensions/commit/e5d628ea2962b6e8f27489007a2a21fe360c8991

Sorry for the delay in cocoapods update, I'll include this change in the next build
