### ISSUE TITLE
Argument labels '(x:, y:, w:, h:)' do not match any available overloads`

### ISSUE THREAD

**Issue by mezhevikin** [goktugyil/EZSwiftExtensions#404]
Hello. I have error on xcode 8.3:

`/Users/mezhevikin/Desktop/Projects/horoscope/Horoscope/Views/FriendCell.swift:36:25: Argument labels '(x:, y:, w:, h:)' do not match any available overloads`

Code:
```
iconImageView = UIImageView(
            x: 10,
            y: 10,
            w: 60,
            h: 60
)
```

xcode 8.3, any ios, EZSwiftExtensions 1.9

**Comment by Khalian** [comment]
Hey, https://github.com/goktugyil/EZSwiftExtensions/blob/master/Sources/UIImageViewExtensions.swift#L13. I dont see any of the constructors not accept either the imageName or the UIImage object as arg. 

What that would mean is that the view is a clipped representation of the actual image, which is missing in your args.

**Comment by mezhevikin** [comment]
@Khalian UIImageView this is a child of UIView, and UIView contains method:

https://github.com/goktugyil/EZSwiftExtensions/blob/master/Sources/UIViewExtensions.swift#L14

**Comment by Khalian** [comment]
Ok I will take a look.

**Comment by Khalian** [comment]
https://github.com/goktugyil/EZSwiftExtensions/pull/408

Curious, unit testing your hypothesis reveals nothing wrong. Could you let me know if this helps?
