### ISSUE TITLE
need to update for swift 3.1

### ISSUE THREAD

**Issue by Eric0625** [goktugyil/EZSwiftExtensions#405]
'DBL_MAX' is deprecated: Please use 'Double.greatestFiniteMagnitude' or '.greatestFiniteMagnitude'.

**Comment by Khalian** [comment]
Thanks Eric. This has been fixed in https://github.com/goktugyil/EZSwiftExtensions/commit/d475a43ed13653142ce1544b19f34061b47dda76 and now in mainline branch.
