### ISSUE TITLE
Lose "public"

### ISSUE THREAD

**Issue by taogeyijiu** [goktugyil/EZSwiftExtensions#421]
UIAlertControllerExtensions:
extension UIAlertController {
    /// EZSE: Easy way to present UIAlertController
    func show() {
        UIApplication.shared.keyWindow?.rootViewController?.present(self, animated: true, completion: nil)
    }
}
And StringExtensions:
 ///EZSE: Returns hight of rendered string
    func height(_ width: CGFloat, font: UIFont, lineBreakMode: NSLineBreakMode?) -> CGFloat {
        var attrib: [String: AnyObject] = [NSFontAttributeName: font]
        if lineBreakMode != nil {
            let paragraphStyle = NSMutableParagraphStyle()
            paragraphStyle.lineBreakMode = lineBreakMode!
            attrib.updateValue(paragraphStyle, forKey: NSParagraphStyleAttributeName)
        }
        let size = CGSize(width: width, height: CGFloat(DBL_MAX))
        return ceil((self as NSString).boundingRect(with: size, options: NSStringDrawingOptions.usesLineFragmentOrigin, attributes:attrib, context: nil).height)
    }

This two method is do not work, why?

**Comment by Khalian** [comment]
Not sure I understand the premise of this question. Is it that these methods are not accessible to callers ? Or is there a runtime failure of some sorts?

**Comment by taogeyijiu** [comment]
methods are not accessible to callers ,I use cocoapods

**Comment by taogeyijiu** [comment]
methods are not accessible to callers ,I use cocoapods

**Comment by taogeyijiu** [comment]
[](url)
<img width="695" alt="wx20170515-103716 2x" src="https://cloud.githubusercontent.com/assets/17825349/26040773/990dd476-395a-11e7-9fb3-f4aa8b53d143.png">

**Comment by Khalian** [comment]
gotcha. I will fix that oversight.

**Comment by taogeyijiu** [comment]
ok

**Comment by Khalian** [comment]
So string height has been recently fixed in https://github.com/goktugyil/EZSwiftExtensions/commit/2395fa54

I will put out a PR for the other one.

**Comment by taogeyijiu** [comment]
<img width="844" alt="wx20170515-110808 2x" src="https://cloud.githubusercontent.com/assets/17825349/26041365/d6ccb5ee-395e-11e7-8581-f63f9041f3a5.png">
