### ISSUE TITLE
 Library conflict

### ISSUE THREAD

**Issue by shanyanhai** [goktugyil/EZSwiftExtensions#423]
I like your library,
It's convenient and saves me a lot of time.
Now I have another question
This question may not be asked here, but I don't know where to find the answer
I use the Carthage
import EZSwiftExtensions
import Material  (Other libraries)
There's the same
extension UIView {
      var x:......
}
If I use
UiView ().x --------(Xcode will report the error ambiguous of)
I try   
UIView().EZSwiftExtensions.x 
OR
EZSwiftExtensions.UIView().x
are error
How do I write?
Or you should add a prefix or suffix to avoid future encounters

**Comment by Khalian** [comment]
I am glad you like our library. 

So I have handled something similar to this before https://github.com/goktugyil/EZSwiftExtensions/issues/353

The gist from that is that we do not hold an opinion about other frameworks. You are most likely importing something from another library that defines an extension with the same name but a different implementation. 

You can take a look at this thread : http://stackoverflow.com/questions/33892897/name-collisions-for-extension-methods-from-different-frameworks for possible resolutions.

**Comment by Khalian** [comment]
@shanyanhai Does that answer your question ?

**Comment by shanyanhai** [comment]
@Khalian       I try  
That kind of writing is in Xcode8.3.2   (error)
But my problem has been solved, I decided to delete "Material".  - -!
Thank you in the end.You try hard to help,and "Carthage" just said: "find other" . (kicking a ball - -!). Maybe I'll use cocoapods later, because Carthage doesn't seem to be very mature, Carthage.

**Comment by Khalian** [comment]
I dont think this is a cathage or cocoapods issues. Its an extensions clash.
The only issue with carthage it seems is its lack of descriptive error messages. 

I am closing this for now. Feel free to reach out if you any followups or other issues.
