### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by astrokin** [goktugyil/EZSwiftExtensions#430]
Do you have any plans to support MacOS ?

**Comment by Khalian** [comment]
Good point. We have had this conversation before : https://github.com/goktugyil/EZSwiftExtensions/issues/337. 

I have been putting this off for a while. But since it bothers people, I will prioritize this in my free time.

**Comment by Khalian** [comment]
I started the work at https://github.com/goktugyil/EZSwiftExtensions/pull/431. I will close this in favor of https://github.com/goktugyil/EZSwiftExtensions/pull/337
