### ISSUE TITLE
Carthage can't compile

### ISSUE THREAD

**Issue by icefall** [goktugyil/EZSwiftExtensions#452]
Steps to reproduce the problem:
- Create an iOS project
- Create `Cartfile` and adds `github "goktugyil/EZSwiftExtensions"`
- `carthage update EZSwiftExtensions --platform ios`

Using Carthage 0.25.0

```
➜  TestCarthage git:(master) ✗ carthage update --platform ios
*** Fetching EZSwiftExtensions
*** Checking out EZSwiftExtensions at "1.11"
*** xcodebuild output can be found in /var/folders/8b/dspfzsq952x7rzvsmlpv2vdc0000gn/T/carthage-xcodebuild.byR5gt.log
*** Building scheme "EZSwiftExtensions-iOS" in EZSwiftExtensions.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/carlbrusell/Projects/TestCarthage/Carthage/Checkouts/EZSwiftExtensions/EZSwiftExtensions.xcworkspace -scheme EZSwiftExtensions-iOS -configuration Release -derivedDataPath /Users/carlbrusell/Library/Caches/org.carthage.CarthageKit/DerivedData/8.3.3_8E3004b/EZSwiftExtensions/1.11 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/carlbrusell/Projects/TestCarthage/Carthage/Checkouts/EZSwiftExtensions)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/8b/dspfzsq952x7rzvsmlpv2vdc0000gn/T/carthage-xcodebuild.byR5gt.log
```

The log is [carthage-xcodebuild.byR5gt.log.txt](https://github.com/goktugyil/EZSwiftExtensions/files/1281023/carthage-xcodebuild.byR5gt.log.txt)

**Comment by borkuslav** [comment]
I guess here is the reason: 
/Users/carlbrusell/Projects/TestCarthage/Carthage/Checkouts/EZSwiftExtensions/Sources/UIButtonExtensions.swift:16:47: error: Superfluous Disable Command Violation: SwiftLint rule 'function_parameter_count' did not trigger a violation in the disabled region. Please remove the disable command. (superfluous_disable_command)

**Comment by icefall** [comment]
@borkuslav thanks!

EZSwiftExtensions uses Swiftlint and it is violating one of the rules. We have to ways to deal with this:

- Remove `function_parameter_count` which is being called but did not trigger any violation.
- Disable `superfluous_disable_command` for the whole project.

Which path is the best one here?

I can manage to do a pull request with those changes.

**Comment by lfarah** [comment]
These were already fixed in #444.
@Khalian we need to launch a new version so @icefall, @borkuslav and other Carthage users can use the app. Should we wait for any other PR or I can launch ```1.12``` right now?

**Comment by Khalian** [comment]
@lfarah  Na. Go ahead.

**Comment by icefall** [comment]
Looks like this is already fixed
