### ISSUE TITLE
Update cocoapod file to latest release

### ISSUE THREAD

**Issue by CrislerAnytimes** [goktugyil/EZSwiftExtensions#482]
Hi can someone update the latest podfile to the latest release? (1.12)

**Comment by isimple4** [comment]
For now you can use `master` branch or `1.12` tag branch.

**Comment by goktugyil** [comment]
https://github.com/goktugyil/EZSwiftExtensions/issues/481

**Comment by lizhaobomb** [comment]
pod can't find 1.12

**Comment by isimple4** [comment]
It seems that `1.12` branch has not been merged and published yes, try using `tag` like below.

`pod 'EZSwiftExtensions', :git => 'https://github.com/goktugyil/EZSwiftExtensions.git', :tag => '1.12'
`

#483
