### ISSUE TITLE
UIFont.HelveticaNeue(type: .Regular, size: 13), unexpectedly found nil while

### ISSUE THREAD

**Issue by oronbz** [goktugyil/EZSwiftExtensions#49]
Hi,
When trying to run `UIFont.HelveticaNeue(type: .Regular, size: 13)` getting: `fatal error: unexpectedly found nil while unwrapping an Optional value`

**Comment by goktugyil** [comment]
Thanks, I'll look into it

**Comment by lfarah** [comment]
I discovered why this happens. It's because HelveticaNeue doesn't have a -Regular. Its name is just HelveticaNeue. I'm fixing that right now
