### ISSUE TITLE
Support for Swift 5

### ISSUE THREAD

**Issue by JQHee** [goktugyil/EZSwiftExtensions#498]
Whether planned adaptation swift 5?

**Comment by goktugyil** [comment]
An update for 5 is coming: https://github.com/goktugyil/EZSwiftExtensions/pull/501

**Comment by ceeyang** [comment]
U can use this branch befor the new version Pull Request completed.
```
pod 'EZSwiftExtensions', :git => 'https://github.com/ceeyang/EZSwiftExtensions.git', :branch => 'Swift5.0'
```
