### ISSUE TITLE
NSAttributedString Extensions

### ISSUE THREAD

**Issue by thellimist** [goktugyil/EZSwiftExtensions#56]
Having `NSAttributedString` properties in String Extension would be useful. Some examples could be

```
let myStr = "Hello World"
let attrStr1 = myStr.undeline()
let attrStr2 = myStr.bold()
let attrStr3 = myStr.italic()
let attrStr4 = myStr[0...6].italic()
let attrStr5 = myStr[7...10].color(UIColor.greenColor())
let attrStr6 = myStr.link("www.google.com") // or href("www.google.com")
let attrStr7 = attrStr4.add(attrStr5).add(attrStr6)
```

Also chaining could be great. This would require extensions in both `NSAttributedString` and `String`
```
let attrStr1 = myStr.undeline().italic().link("www.google.com")
```

**Comment by lfarah** [comment]
UILabels won't open links. Need to set delegates to make it work!

**Comment by lfarah** [comment]
Tasklist:
- [x] underline
- [x] bold
- [x] italic
- [x] color
- [x] chaining by using NSAttributedString Extensions

**Comment by lfarah** [comment]
@goktugyil I think we can close this issue
