### ISSUE TITLE
Carthage Support?

### ISSUE THREAD

**Issue by fbuentello** [goktugyil/EZSwiftExtensions#6]
Im really excited for this repo, but I am wondering if there will be Carthage support anytime soon?

**Comment by MPiccinato** [comment]
+1

**Comment by goktugyil** [comment]
If you know how to implement it feel free to do it and send a pull request. If not I'll check it out, probably this weekend.

**Comment by goktugyil** [comment]
Guys I pushed the commit by @bcylin , it works fine with me. Please try it out and see if there are any problems
https://github.com/goktugyil/EZSwiftExtensions/pull/9

**Comment by fbuentello** [comment]
Yea worked for me! 👍🏼
