### ISSUE TITLE
UIView.removeSubview(x,y)

### ISSUE THREAD

**Issue by lfarah** [goktugyil/EZSwiftExtensions#90]
Normally, you can only remove a subview if you have the _object_. In this method, you can remove a subview by having it's **x** and **y**
What do you guys think?

``` swift
extension UIView {
  func removeSubview(x:Double,y:Double) {
    for view in self.subviews {
      if Float(view.frame.origin.x) == Float(x) && Float(view.frame.origin.y) == Float(y) {
        view.removeFromSuperview()
        "removed"
      }
    }
  }
}
```

**Comment by goktugyil** [comment]
This seems dangerous. What if there is another subview at that location?
